### ISSUE TITLE
"Requested resource is not available in current API version"

### ISSUE THREAD

**Issue by slavapvf** [intercom/intercom-dotnet#163]
hello, tried to use as in example and got:   
"Requested resource is not available in current API version"
at Intercom.Core.Client.Get[T](Dictionary`2 headers, Dictionary`2 parameters, String resource)
   at Intercom.Clients.UsersClient.View(User user)
   at FluentPro.Fbo.Business.InterComService.SetDeletedDate(String customerEmail) in D:\projects\FbOnline\Sources\FluentPro.Fbo\FluentPro.Fbo.Business\Services\InterComService.cs:line 41

**Comment by hognevevle** [comment]
Sadly, this repo doesn't seem to be maintained anymore. Consequently, it doesn't support the latest API (2.0). Best bet is to either use it as-is for API 1.4, or fork it and implement the missing features you need from 2.0.

**Comment by lloydliyu** [comment]
Hi @slavapvf  👋 As said, we don't have a timeline on this for the dotnet SDK to be updated to support version 2.x of our API yet. However, if anybody wants to give it a shot and add support for version 2.0, feel free to jump in and leave a note here so we are all aligned and we don't do double work 😃

We'll let you know here when we start working on it. In the meantime, if you need help changing your app version to 1.x within the Developer hub, feel free to reach out to the support team using the Messenger on https://intercom.com who can help you with the steps on that.
