### ISSUE TITLE
Could not load type RestSharp.HttpBasicAuthenticator

### ISSUE THREAD

**Issue by Skaelv** [intercom/intercom-dotnet#36]
Customer using the C# API wrapper has an issue with `RestSharp`.
 It has stopped working recently with an error `Could not load type RestSharp.HttpBasicAuthenticator from assembly  RestSharp, Version=105.2.2.0, Culture=neutral, PublicKeyToken=null'. at IntercomDotNet.Client.GetRestClient()`

Customer's hint is that RestSharp have changed the namespace for the HttpBasicAuthenticator.
So he was able to fix by downgrading version but his Twilio integration requires a new version of RestSharp.

**Comment by purushothamm** [comment]
I am also facing below error with Jira.SDK, please help resolving it.
System.TypeLoadException was unhandled
  HResult=-2146233054
  Message=Could not load type 'RestSharp.HttpBasicAuthenticator' from assembly 'RestSharp, Version=105.2.3.0, Culture=neutral, PublicKeyToken=null'.
  Source=Jira.SDK
  TypeName=RestSharp.HttpBasicAuthenticator
  StackTrace:
       at Jira.SDK.JiraClient..ctor(String url, String username, String password)
       at Jira.SDK.Jira.Connect(String url, String username, String password)
       at JiraRestDMS.jiraIssues.button1_Click(Object sender, EventArgs e)
       at System.Windows.Forms.Control.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
       at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.ButtonBase.WndProc(Message& m)
       at System.Windows.Forms.Button.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.Run(Form mainForm)
       at JiraRestDMS.Program.Main()
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by purushothamm** [comment]
this issue got resolved by rolling back to RestSharp Version=105.0.1

**Comment by choran** [comment]
Cool, thanks for the update. Just getting back to closing our some issues now so will close this.
